### ISSUE TITLE
Animation jumps in the beginning (example)

### ISSUE THREAD

**Issue by Gargo** [iamshezad/SHTransition#3]
I used iphone 5s simulator and "slow animations" option (cmd+T).
All the elements jump into other positions and only then the animation becomes smooth

**Comment by iamshezad** [comment]
I have solved the glitch in transition animation 
but sorry this doesn't work in slow animation mode
this completely work fine in normal mode

**Comment by Gargo** [comment]
@iamshezad i mean you can use "slow transitions" to check what is going wrong. Without this option the animation jumps too but it is harder to see it

**Comment by iamshezad** [comment]
it was working fine with iOS 10 but now the issue is with the transition animation.
i'm working on that but for now i have reduced the transition time so it looks good.

**Comment by iamshezad** [comment]
@Gargo the code has been updated again 
let me know if there is any other issues
